modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
[[mods]]
    modId="forge-bug6692"
    version="${file.jarVersion}"
    displayName="Forge BugFix 6692"
    credits="Thanks for this example mod goes to Java"
    authors="AterAnimAvis"
    description="Potential fix for MinecraftForge#6692"
